name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [win-x64, win-arm64]
        build_framework: [net9.0-windows]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: dotnet of plugin dll
      working-directory: .\RedisPlugin
      run:  dotnet publish -f ${{ matrix.build_framework }} -r ${{ matrix.build_platform }} -c ${{ matrix.build_configuration }}

    - uses: olegtarasov/get-tag@v2.1.4
      id: tagName

    - name: zip artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      run: 7z a RedisPlugin_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip .\RedisPlugin\bin\${{ matrix.build_configuration }}\${{ matrix.build_framework }}\${{ matrix.build_platform }}\publish\*

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v5
      with:
          name: RedisPlugin_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip
          path: RedisPlugin_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip

    - name: Create release on tagging
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: RedisPlugin_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip

